name = "PartiallyObservedMarkovProcesses"
uuid = "32433216-4d85-4b2d-94ed-a614743ba12b"
version = "0.4.9"
authors = ["Aaron A. King <kingaa@umich.edu>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LocalCoverage = "5f6e1e16-694c-5876-87ef-16b5274f298e"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Distributions = "0.25.113"
InvertedIndices = "1.3.0"
LocalCoverage = "0.8.4"
RCall = "0.14.9"
Random = "1.11.0"
julia = "1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LocalCoverage = "5f6e1e16-694c-5876-87ef-16b5274f298e"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
