name = "PartiallyObservedMarkovProcesses"
uuid = "32433216-4d85-4b2d-94ed-a614743ba12b"
version = "0.5.1-3"
authors = ["Aaron A. King <kingaa@umich.edu>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Distributions = "0.25.113"
OrdinaryDiffEq = "6.106.0"
Random = "1.11.0"
SciMLBase = "2.127.0"
julia = "1.11"
